Updated to Factorio 1.1
veger/TLBE pull request #17
Opened 2020-12-29 16:28 UTC by jeison-souza

Hi, I just wrote a quickfix to allow this mod to run on 1.1.

Thanks for the mod btw.

2020-12-29 16:40 UTC, jeison-souza commented
I saw that it seems that another test project of yours is missing some files.

As I just touched a not tested UI format, all tests should work well as before. I hope these modifs can help you to fix this mod to 1.1

I'm gaming with this modified version and had no errors until now.

Thanks

2020-12-29 22:58 UTC, veger commented
Thank you for your contribution.
I'll try to find time to fix the error, it is due to a wrong branch (my PR got accepted and I removed my fork... :disappointed: )

After that we can merge this PR

2021-01-03 13:35 UTC, veger requested changes

2021-01-03 13:35 UTC, veger commented on scripts/gui.lua
> +            sprite = "utility/trash",
You missed a similar change on line 1036

2021-01-03 13:36 UTC, veger commented
Sorry I was a little late(r) but the holidays, kids and some other things messed up my plans... :wink: 
I found a small issue when trying the mod on 1.1, if you can fix it, I'll merge the PR and make a release

2021-01-03 13:37 UTC, veger commented
PS If you (also) merge the updated `master` branch from my repo the tests should work again

2021-01-05 20:07 UTC, veger commented on scripts/gui.lua
> +            sprite = "utility/trash",
I figured out how to update your PR :wink:
Thanks again for your contribution

2021-01-05 20:08 UTC, veger approved these changes

2021-01-05 20:14 UTC, merged

2021-01-07 13:30 UTC, jeison-souza commented
Thanks !

Em ter., 5 de jan. de 2021 às 15:15, Maarten Bezemer <
notifications@github.com> escreveu:

> Merged #17 <https://github.com/veger/TLBE/pull/17> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/veger/TLBE/pull/17#event-4171761491>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA34H5Q5LYHOUH5NXYCENULSYNXMPANCNFSM4VNMC4YQ>
> .
>